### ISSUE TITLE
PhantomJSSetup shutdown hook fails when source dir does not exist

### ISSUE THREAD

**Issue by jpraet** [moodysalem/java-phantomjs-wrapper#9]
```
[WARNING] PhantomJSSetup was unable to clean up temporary directories under: [D:\babun\.babun\cygwin\tmp\java-phantomjs]. Caused by:
java.nio.file.NoSuchFileException: D:\babun\.babun\cygwin\tmp\java-phantomjs\source-c8ec28df-6b5e-403b-9244-b0cdad298dad
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at com.moodysalem.phantomjs.wrapper.PhantomJSSetup$1.run(PhantomJSSetup.java:202)
```

The shutdown hoop attempts to delete these dirs:

```
Files.delete(PhantomJSConstants.TEMP_SOURCE_DIR);
Files.delete(PhantomJSConstants.TEMP_SCRIPT_DIR);
Files.delete(PhantomJSConstants.TEMP_RENDER_DIR);
```

But I'm not using PhantomJS.render(), only PhantomJS.exec(), so the source and render dirs are never created in the first place. And because the deletion of the source dir fails, the scripts dir does not get cleaned up either.

**Comment by moodysalem** [comment]
Would accept a PR for this. Just a check if those exist before deleting.

**Comment by jpraet** [comment]
Could you make a 3.1.3 release?

**Comment by moodysalem** [comment]
I’ll have to do it next week, hope it’s not high priority for you.

**Comment by Staryjir** [comment]
Is this issue fixed? I am facing the same problem....

**Comment by moodysalem** [comment]
Sorry, still haven’t pushed a release. How does the problem manifest?

**Comment by Staryjir** [comment]
I run this stuff from appplication server and i see multiple shutdown messages when the servers stops and an error like this:

2018-08-29 10:50:17,503 INFO  [stdout] (Thread-145) Shutting down PhantomJS instance

2018-08-29 10:50:17,504 INFO  [stdout] (Thread-144) Shutting down PhantomJS instance

2018-08-29 10:50:17,504 INFO  [stdout] (Thread-149) Shutting down PhantomJS instance

2018-08-29 10:50:17,504 WARN  [com.moodysalem.phantomjs.wrapper.PhantomJSSetup] (PhantomJSSetupShutDownHook) PhantomJSSetup was unable to clean up temporary directories under: [C:\Users\jstary\AppData\Local\Temp\java-phantomjs]. Caused by: : java.nio.file.NoSuchFileException: C:\Users\jstary\AppData\Local\Temp\java-phantomjs\source-7485e9db-421f-4d7e-b5a2-35ff816ef5d7
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at com.moodysalem.phantomjs.wrapper.PhantomJSSetup$1.run(PhantomJSSetup.java:202)

2018-08-29 10:50:17,509 INFO  [stdout] (Thread-148) Shutting down PhantomJS instance

2018-08-29 10:50:17,509 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested via an OS signal
2018-08-29 10:50:17,511 INFO  [stdout] (Thread-142) Shutting down PhantomJS instance

2018-08-29 10:50:17,528 INFO  [com.gemalto.ics.rnd.pm.wildfly.cluster.HASchedulerSingletonService] (MSC service thread 1-2) This node [standalone-PM] should not provide singleton services anymore.
2018-08-29 10:50:17,533 INFO  [stdout] (Thread-150) Shutting down PhantomJS instance

2018-08-29 10:50:17,535 INFO  [stdout] (Thread-147) Shutting down PhantomJS instance

2018-08-29 10:50:17,537 INFO  [stdout] (Thread-146) Shutting down PhantomJS instance


After reading this error report i created a workaround - basically i create these folders by hand at server startup

                Path directory1 = Files.createDirectories(PhantomJSConstants.TEMP_SOURCE_DIR);
                Path directory2 = Files.createDirectories(PhantomJSConstants.TEMP_SCRIPT_DIR);
                Path directory3 = Files.createDirectories(PhantomJSConstants.TEMP_RENDER_DIR);

And then some cleanup logic at the end to get rid of these empty directories in \java-phantomjs
otherwise there will be a lot of empty directories in there - i just mark everything in these dirs as deleteonexit()

**Comment by Staryjir** [comment]
Oh and if i apply the workaround then there is only one message saying PhantomJS is shutting down

**Comment by moodysalem** [comment]
I release 3.1.3 which is supposed to fix this
